---

nginx_server_name: "{{ inventory_hostname }}"
nginx_ssl_dest_dir: /etc/ssl
nginx_strong_dh_group: true  # Strongly recomended in production. See weakdh.org.
nginx_use_letsencrypt: false

# Only used when nginx_use_letsencrypt is set to yes/true. The 'certbot' role will automatically generate these files.
api_letsencrypt_dir: "/etc/letsencrypt/live/{{ api_url }}"
mutual_tls_letsencrypt_dir: "/etc/letsencrypt/live/{{ mutual_tls_api_url }}"
letsencrypt_cert_filename: fullchain.pem
letsencrypt_privkey_filename: privkey.pem

flask_virtualenv_path: "/webapps/{{ flask_application_name }}"
django_virtualenv_path: "/webapps/{{ django_application_name }}"

# "Security Header Endpoint" from "Client Keys" in Sentry
security_header_endpoint: null
