---

- name: Make sure the latest npm is installed
  apt: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm
  tags:
    - packages

- name: Ensure JS+CSS compressors installed
  npm: name={{ item }} global=yes
  with_items:
    - uglify-js
    - yuglify
  tags:
    - packages

- name: Install dependencies with npm
  npm:
    path: "{{ project_path }}"
    production: yes

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Copy over the Google API credentials
  template: src=oauth_credentials.j2
            dest={{ project_path }}/oauth_credentials.json
            owner=root
            group=root
            mode=0400
  when: oauth_private_key is defined

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
    database: "{{ item }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  with_items:
    - default
    - auth_db
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  notify: restart application
  tags: django.collectstatic
