---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Configure SSH
  template: src=sshd_config.j2
            dest=/etc/ssh/sshd_config
            mode=0644
            backup=yes
  notify:
    - restart ssh

- name: Install security updates
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags:
    - packages
    - skip_ansible_lint

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - "{{ base_python_package }}-pip"
    - "i{{ base_python_package }}"
    - supervisor
  tags:
    - packages
    - packages.security

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
    - skip_ansible_lint
